"""empty message

Revision ID: 09b0e0a8f1d5
Revises: 48a7e8d80479
Create Date: 2025-03-05 13:12:30.840023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b0e0a8f1d5'
down_revision: Union[str, None] = '48a7e8d80479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('rows', sa.Integer(), nullable=False))
    op.add_column('showtimes', sa.Column('places', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('row', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('place', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'place')
    op.drop_column('tickets', 'row')
    op.drop_column('showtimes', 'places')
    op.drop_column('showtimes', 'rows')
    # ### end Alembic commands ###
