"""empty message

Revision ID: 17eb62b72b6e
Revises: 1cc6549acbb5
Create Date: 2025-03-13 14:11:51.407258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17eb62b72b6e'
down_revision: Union[str, None] = '1cc6549acbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('rows', sa.Integer(), nullable=False))
    op.add_column('halls', sa.Column('places', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('ticket_url', sa.String(), nullable=True))
    op.alter_column('showtimes', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('showtimes', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('orders', 'ticket_url')
    op.drop_column('halls', 'places')
    op.drop_column('halls', 'rows')
    # ### end Alembic commands ###
