"""empty message

Revision ID: 1cc6549acbb5
Revises: 9dc22d1b4af5
Create Date: 2025-03-05 14:11:25.290110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc6549acbb5'
down_revision: Union[str, None] = '9dc22d1b4af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('tickets', 'is_booked')
    op.drop_column('tickets', 'seat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seat_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('showtimes', 'price')
    # ### end Alembic commands ###
