"""empty message

Revision ID: 48a7e8d80479
Revises: f3c8cb547492
Create Date: 2025-02-15 23:29:38.252942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a7e8d80479'
down_revision: Union[str, None] = 'f3c8cb547492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtimes', 'available_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('available_tickets', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
