"""empty message

Revision ID: 6d1794057fcb
Revises: 17eb62b72b6e
Create Date: 2025-03-14 13:48:36.566169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1794057fcb'
down_revision: Union[str, None] = '17eb62b72b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_ticket_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('payments_booking_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_booking_id_fkey', 'payments', 'bookings', ['booking_id'], ['id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_ticket_id_fkey', 'bookings', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
