"""Insert some data for example

Revision ID: 85474a72ca06
Revises: d3464dca3ef1
Create Date: 2025-03-15 01:10:50.045956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85474a72ca06'
down_revision: Union[str, None] = 'd3464dca3ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    films_data = [
        {"id": 1, "name": "Inception", "genre": "Sci-Fi", "duration": 148, "age_restriction": "PG-13", "imdb_rating": 8.8,
         "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1898899/27ed5c19-a045-49dd-8624-5f629c5d96e0/600x900"},
        {"id": 2, "name": "The Dark Knight", "genre": "Action", "duration": 152, "age_restriction": "PG-13", "imdb_rating": 9.0,
         "description": "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/3560b757-9b95-45ec-af8c-623972370f9d/600x900"},
        {"id": 3, "name": "Pulp Fiction", "genre": "Crime", "duration": 154, "age_restriction": "R", "imdb_rating": 8.9,
         "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1900788/87b5659d-a159-4224-9bff-d5a5d109a53b/600x900"},
        {"id": 4, "name": "Forrest Gump", "genre": "Drama", "duration": 142, "age_restriction": "PG-13", "imdb_rating": 8.8,
         "description": "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1599028/0fa5bf50-d5ad-446f-a599-b26d070c8b99/600x900"},
        {"id": 5, "name": "The Matrix", "genre": "Sci-Fi", "duration": 136, "age_restriction": "R", "imdb_rating": 8.7,
         "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/8ab9a119-dd74-44f0-baec-0629797483d7/600x900"},
        {"id": 6, "name": "Harry Potter and the Philosopher's Stone", "genre": "Fantasy", "duration": 152,
         "age_restriction": "PG", "imdb_rating": 7.6,
         "description": "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family, and the terrible evil that haunts the magical world.",
         "poster_url": "https://avatars.mds.yandex.net/get-kinopoisk-image/4774061/cf1970bc-3f08-4e0e-a095-2fb57c3aa7c6/600x900"}
    ]
    op.bulk_insert(sa.table('films',
                            sa.Column('id', sa.Integer, primary_key=True),
                            sa.Column('name', sa.String, nullable=False),
                            sa.Column('genre', sa.String, nullable=False),
                            sa.Column('duration', sa.Integer, nullable=False),
                            sa.Column('age_restriction', sa.String, nullable=False),
                            sa.Column('imdb_rating', sa.Float, nullable=True),
                            sa.Column('description', sa.String, nullable=True),
                            sa.Column('poster_url', sa.String, nullable=True)),
                   films_data)

    showtimes_data = [
        {"film_id": 1, "datetime": "2025-03-20 14:00:00", "total_tickets": 80, "rows": 8, "places": 10,
         "price": 12.50},
        {"film_id": 1, "datetime": "2025-03-20 16:30:00", "total_tickets": 84, "rows": 7, "places": 12, "price": 15.00},
        {"film_id": 4, "datetime": "2025-03-20 16:30:00", "total_tickets": 78, "rows": 6, "places": 13, "price": 13.50},
        {"film_id": 2, "datetime": "2025-03-20 19:00:00", "total_tickets": 80, "rows": 8, "places": 10, "price": 10.00},
        {"film_id": 3, "datetime": "2025-03-21 11:00:00", "total_tickets": 65, "rows": 5, "places": 13, "price": 14.00},
        {"film_id": 5, "datetime": "2025-03-21 13:30:00", "total_tickets": 96, "rows": 8, "places": 12, "price": 13.75},
        {"film_id": 6, "datetime": "2025-03-21 16:00:00", "total_tickets": 64, "rows": 8, "places": 8,
         "price": 12.00},
        {"film_id": 2, "datetime": "2025-03-21 19:00:00", "total_tickets": 77, "rows": 7, "places": 11, "price": 10.00},
        {"film_id": 6, "datetime": "2025-03-21 19:00:00", "total_tickets": 48, "rows": 8, "places": 6, "price": 12.00}
    ]
    op.bulk_insert(sa.table('showtimes',
                            sa.Column('id', sa.Integer, primary_key=True),
                            sa.Column('film_id', sa.Integer, sa.ForeignKey("films.id")),
                            sa.Column('datetime', sa.DateTime, nullable=False),
                            sa.Column('total_tickets', sa.Integer, nullable=False),
                            sa.Column('rows', sa.Integer, nullable=False),
                            sa.Column('places', sa.Integer, nullable=False),
                            sa.Column('price', sa.Numeric(10, 2), nullable=False)),
                   showtimes_data)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM showtimes")
    op.execute("DELETE FROM films")
    # ### end Alembic commands ###
