"""empty message

Revision ID: 9dc22d1b4af5
Revises: 09b0e0a8f1d5
Create Date: 2025-03-05 13:29:04.910519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc22d1b4af5'
down_revision: Union[str, None] = '09b0e0a8f1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('showtimes_hall_id_fkey', 'showtimes', type_='foreignkey')
    op.drop_column('showtimes', 'hall_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('hall_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('showtimes_hall_id_fkey', 'showtimes', 'halls', ['hall_id'], ['id'])
    # ### end Alembic commands ###
